package DLMSIdl;


/**
* DLMSIdl/DLMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DLMS.idl
* Thursday, 7 March, 2019 1:21:05 AM IST
*/

public interface DLMSOperations 
{
  String addItem (String managerID, String itemID, String itemName, int quantity);
  String removeItem (String managerID, String itemID, int quantity);
  String borrowItem (String userID, String itemID, int numberOfDays);
  String returnItem (String userID, String itemID);
  String addToQueue (String userID, String itemID);
  String findItem (String userID, String itemName);
  String printLibrary (String managerID);
  void initialize (String userID, String itemName);
  void startServer ();
  String getStatus ();
  String checkBorrowList (String userID, String itemID);
  String checkBookAvailability (String itemID);
} // interface DLMSOperations
