package DLMSIdl;


/**
* DLMSIdl/DLMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DLMS.idl
* Thursday, 7 March, 2019 1:21:05 AM IST
*/

public interface DLMS extends DLMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DLMS
