package DLMSIdl;


/**
* DLMSIdl/DLMSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DLMS.idl
* Thursday, 7 March, 2019 1:21:05 AM IST
*/

public abstract class DLMSPOA extends org.omg.PortableServer.Servant
 implements DLMSIdl.DLMSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addItem", new java.lang.Integer (0));
    _methods.put ("removeItem", new java.lang.Integer (1));
    _methods.put ("borrowItem", new java.lang.Integer (2));
    _methods.put ("returnItem", new java.lang.Integer (3));
    _methods.put ("addToQueue", new java.lang.Integer (4));
    _methods.put ("findItem", new java.lang.Integer (5));
    _methods.put ("printLibrary", new java.lang.Integer (6));
    _methods.put ("initialize", new java.lang.Integer (7));
    _methods.put ("startServer", new java.lang.Integer (8));
    _methods.put ("getStatus", new java.lang.Integer (9));
    _methods.put ("checkBorrowList", new java.lang.Integer (10));
    _methods.put ("checkBookAvailability", new java.lang.Integer (11));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DLMSIdl/DLMS/addItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         String itemName = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.addItem (managerID, itemID, itemName, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DLMSIdl/DLMS/removeItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.removeItem (managerID, itemID, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DLMSIdl/DLMS/borrowItem
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         int numberOfDays = in.read_long ();
         String $result = null;
         $result = this.borrowItem (userID, itemID, numberOfDays);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DLMSIdl/DLMS/returnItem
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         String $result = null;
         $result = this.returnItem (userID, itemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DLMSIdl/DLMS/addToQueue
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         String $result = null;
         $result = this.addToQueue (userID, itemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DLMSIdl/DLMS/findItem
       {
         String userID = in.read_string ();
         String itemName = in.read_string ();
         String $result = null;
         $result = this.findItem (userID, itemName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // DLMSIdl/DLMS/printLibrary
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.printLibrary (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // DLMSIdl/DLMS/initialize
       {
         String userID = in.read_string ();
         String itemName = in.read_string ();
         this.initialize (userID, itemName);
         out = $rh.createReply();
         break;
       }

       case 8:  // DLMSIdl/DLMS/startServer
       {
         this.startServer ();
         out = $rh.createReply();
         break;
       }

       case 9:  // DLMSIdl/DLMS/getStatus
       {
         String $result = null;
         $result = this.getStatus ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // DLMSIdl/DLMS/checkBorrowList
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         String $result = null;
         $result = this.checkBorrowList (userID, itemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 11:  // DLMSIdl/DLMS/checkBookAvailability
       {
         String itemID = in.read_string ();
         String $result = null;
         $result = this.checkBookAvailability (itemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DLMSIdl/DLMS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DLMS _this() 
  {
    return DLMSHelper.narrow(
    super._this_object());
  }

  public DLMS _this(org.omg.CORBA.ORB orb) 
  {
    return DLMSHelper.narrow(
    super._this_object(orb));
  }


} // class DLMSPOA
