package DLMSIdl;

/**
* DLMSIdl/DLMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DLMS.idl
* Thursday, 7 March, 2019 1:21:05 AM IST
*/

public final class DLMSHolder implements org.omg.CORBA.portable.Streamable
{
  public DLMSIdl.DLMS value = null;

  public DLMSHolder ()
  {
  }

  public DLMSHolder (DLMSIdl.DLMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DLMSIdl.DLMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DLMSIdl.DLMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DLMSIdl.DLMSHelper.type ();
  }

}
